name: Docker Image Sync

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '0 0 * * 1' # 每周一自动执行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Aliyun
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_USER_NAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Pull and Push Images
        run: |
          # 在这里定义你需要同步的镜像： 原始镜像名称 -> 目标镜像标签名
          IMAGES=(
            "mysql:8.4.9"
            "redis:latest"
            "nginx:stable"
          )

          for IMAGE in "${IMAGES[@]}"; do
            # 拉取
            docker pull $IMAGE
            # 打标签 (将 docker.io/library/nginx 变为 crpi-xxx.xxx/my-mirrors/nginx)
            NEW_IMAGE="${{ secrets.ALIYUN_REGISTRY }}/naceyeve/${IMAGE##*/}"
            docker tag $IMAGE $NEW_IMAGE
            # 推送
            docker push $NEW_IMAGE
            echo "Sync completed: $NEW_IMAGE"
          done
